# Generated by Django 4.0.6 on 2022-07-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
