# Generated by Django 4.0.6 on 2022-07-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_donation_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatedpeople',
            old_name='time',
            new_name='added',
        ),
    ]
