# Generated by Django 4.0.6 on 2022-07-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_donation_money_need'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
