# Generated by Django 4.0.6 on 2022-07-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_clientmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessages',
            name='message',
            field=models.CharField(max_length=512),
        ),
    ]
