# Generated by Django 4.0.6 on 2022-07-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_clientmessages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessages',
            name='phone_number',
            field=models.TextField(max_length=15),
        ),
    ]
